name: ASP.NET Core CI/CD to IIS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./Test/MyApp/MyApp.csproj

    - name: Build
      run: dotnet build ./Test/MyApp/MyApp.csproj --configuration Release --no-restore

    # - name: Run tests
    #   run: dotnet ./Test/MyApp/MyApp.csproj --no-build --verbosity normal

    - name: Publish
      run: dotnet publish ./Test/MyApp/MyApp.csproj -c Release -o ./publish

    - name: Install WebDeploy 
      run: | 
        choco install webdeploy --yes

    - name: Deploy to IIS via WebDeploy
      run: |
        msdeploy.exe -verb:sync -source:contentPath="./publish" `
        -dest:auto,computerName="http://46.245.69.106:9010/msdeploy.axd?site=Test",userName="$env:DEPLOY_USER",password="$env:DEPLOY_PASS",authType="Basic" `
        -allowUntrusted
      env:
        DEPLOY_USER: ${{ secrets.IIS_USER }}
        DEPLOY_PASS: ${{ secrets.IIS_PASS }}
